version: '3.8'

services:
  backend:
    build:
      context: ./backendb
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb+srv://Abdullah:Abdullah123@cluster0.seiqc.mongodb.net/myapp
      JWT_SECRET: supersecretkey123!

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
