apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
      - name: myapp-frontend
        image: abdullaharif1/myapp-frontend:latest  # Replace with your image
        imagePullPolicy: IfNotPresent  # This line is important
        ports:
        - containerPort: 80
